Acc 3
team-5-tutor-project/team-5-account pull request #17
Opened 2022-05-27 19:01 UTC by deworldgreen123

Closes #3

2022-05-28 15:45 UTC, kawwik requested changes

2022-05-28 15:45 UTC, kawwik commented on TutorProject.Account.Web/Controllers/HomeController.cs
>      public class HomeController : Controller
Переименуй контроллер по его назначению

2022-05-28 15:45 UTC, kawwik commented on TutorProject.Account.Web/Controllers/Dto/Client/ClientSignInDto.cs
> +        public Guid Id { get; set; }
Зачем ID в DTO?

2022-05-28 15:45 UTC, kawwik commented on TutorProject.Account.BLL/Tutors/Services/ITutorService.cs
> +        Task<Guid> SignUp(Tutor tutor);
Плохо в контроллере создавать бизнес-сущности.
Сделай класс SignUpData и передавай сюда

2022-05-28 15:45 UTC, kawwik commented on TutorProject.Account.BLL/Clients/Services/IClientService.cs
> +        Task<Guid> SignUp(Client client);
Аналогично

2022-05-28 15:45 UTC, kawwik commented on TutorProject.Account.Web/Controllers/HomeController.cs
> +            var client = _mapper.Map<Client>(ClientSignIn);
Тут тоже самое. Класс Client отражает логическую модель клиента, нельзя его использовать для передачи логина с паролем. Создай сущность LoginData и передавай в сервис.

2022-05-28 15:45 UTC, kawwik commented on TutorProject.Account.Web/Controllers/HomeController.cs
>          public HomeController(TutorContext tutorContext)
В целом по иерархии папок.
Удобнее для каждого контроллера создавать одноимённую папку. В ней хранить сам контроллер и DTO к нему. Так сразу можно будет найти нужную DTO, не придётся шариться по отдельной папке с вообще всеми дтошками.

Разбей контроллер на TutorController и ClientController. И дтошки закинь соотвественно в их папки

2022-05-28 15:45 UTC, kawwik commented on TutorProject.Account.Web/Controllers/Dto/Tutor/TutorSignInDto.cs
> +    public class TutorSignInDto
Зачем здесь имя и id?

2022-05-28 15:45 UTC, kawwik commented on TutorProject.Account.Web/Controllers/Dto/Tutor/TutorSignUpDto.cs
> +
Убери лишние отступы в моделях и методах

2022-05-29 13:54 UTC, deworldgreen123 commented
plz

2022-05-30 12:48 UTC, kawwik requested changes

2022-05-30 12:48 UTC, kawwik commented on TutorProject.Account.BLL/Clients/Services/ClientService.cs
> +            _context.SaveChangesAsync();
Эвэйтить Пушкин будет?

2022-05-30 12:48 UTC, kawwik commented on TutorProject.Account.BLL/Clients/Services/ClientService.cs
> +            var client = _context.Clients.FindAsync(clientData.Login);
Тут тоже

2022-05-30 12:48 UTC, kawwik commented on TutorProject.Account.BLL/Clients/Dto/ClientLogInDto.cs
> +    public class ClientLogInDto
Пусть это будет не Dto, а Result. Чтобы не путать с вебовскими

2022-05-30 12:48 UTC, kawwik commented on TutorProject.Account.Web/Controllers/TutorController/TutorController.cs
> +    public class TutorController : Controller
Ещё кста надо роуты самих контроллеров прописать.
Допиши к контроллерам аттрибуты по типу [Route("client")]. А то у нас сейчас разные методы на одних эндпоинтах

2022-05-30 18:32 UTC, deworldgreen123 commented
gg

2022-05-30 18:49 UTC, kawwik approved these changes

2022-05-30 18:49 UTC, merged